services:
  - type: web
    name: cs2-sampaguita-sapinosa
    runtime: python
    pythonVersion: 3.14
    buildCommand: pip install -r requirements.txt
    startCommand: python startup.py
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
