# Generated by Django 6.0.4 on 2026-04-26 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, help_text='Staff member assigned to this pickup', limit_choices_to={'role__in': ['admin', 'staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pickups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickup',
            name='user',
            field=models.ForeignKey(help_text='User who requested the pickup', on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickupwastetype',
            name='pickup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pickup'),
        ),
        migrations.AddField(
            model_name='pickupwastetype',
            name='waste_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wastetype'),
        ),
        migrations.AddIndex(
            model_name='pickup',
            index=models.Index(fields=['user'], name='pickups_user_id_025f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='pickup',
            index=models.Index(fields=['date'], name='pickups_date_98e4db_idx'),
        ),
        migrations.AddIndex(
            model_name='pickup',
            index=models.Index(fields=['status'], name='pickups_status_9cc8b9_idx'),
        ),
        migrations.AddIndex(
            model_name='pickup',
            index=models.Index(fields=['priority'], name='pickups_priorit_4ee1f2_idx'),
        ),
        migrations.AddIndex(
            model_name='pickup',
            index=models.Index(fields=['assigned_staff'], name='pickups_assigne_ae4e91_idx'),
        ),
        migrations.AddIndex(
            model_name='pickup',
            index=models.Index(fields=['is_deleted'], name='pickups_is_dele_d7eb22_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pickupwastetype',
            unique_together={('pickup', 'waste_type')},
        ),
    ]
